# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# Initially made by copying homeassistant circleci config.
# yamllint disable rule:line-length rule:document-start
version: 2.1

executors:

  python:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.tag >>
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo

commands:

  docker-prereqs:
    description: Set up docker prerequisite requirement
    steps:
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev

  install-requirements:
    description: Set up venv and install requirements python packages with cache support
    parameters:
      python:
        type: string
        default: latest
      all:
        description: pip install -r requirements.txt
        type: boolean
        default: false
      test:
        description: pip install -r requirements_test_all.txt
        type: boolean
        default: false
    steps:
      - restore_cache:
          keys:
            - v1-<< parameters.python >>-{{ checksum "homeassistant_cli/package_constraints.txt" }}-<<# parameters.all >>{{ checksum "requirements.txt" }}<</ parameters.all>>-<<# parameters.test >>{{ checksum "requirements_test_all.txt" }}<</ parameters.test>>-{{ checksum "setup.py" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -U pip
            pip install -q -U setuptools
            pip install -q -U twine

            <<# parameters.all >>pip install -q --progress-bar off -r requirements.txt -c homeassistant_cli/package_constraints.txt<</ parameters.all>>
            <<# parameters.test >>pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant_cli/package_constraints.txt<</ parameters.test>>
          no_output_timeout: 15m
      - save_cache:
          paths:
            - ./venv
          key: v1-<< parameters.python >>-{{ checksum "homeassistant_cli/package_constraints.txt" }}-<<# parameters.all >>{{ checksum "requirements.txt" }}<</ parameters.all>>-<<# parameters.test >>{{ checksum "requirements_test_all.txt" }}<</ parameters.test>>-{{ checksum "setup.py" }}

  install:
    description: Install Home Assistant CLI
    steps:
      - run:
          name: install
          command: |
            . venv/bin/activate
            pip install -q --progress-bar off -e .

jobs:

  static-check:
    executor:
      name: python
      tag: 3.6-stretch

    steps:
      - checkout
      - docker-prereqs
      - install-requirements:
          python: 3.6-stretch
          test: true

      - run:
          name: run static check
          command: |
            . venv/bin/activate
            black homeassistant_cli tests script

      - run:
          name: run static type check
          command: |
            . venv/bin/activate
            TYPING_FILES=$(cat mypyrc)
            mypy $TYPING_FILES

      - install

  pre-install-all-requirements:
    executor:
      name: python
      tag: 3.6-stretch

    steps:
      - checkout
      - docker-prereqs
      - install-requirements:
          python: 3.6-stretch
          all: true
          test: true

  black:
    executor:
      name: python
      tag: 3.6-stretch
    parallelism: 2

    steps:
      - checkout
      - docker-prereqs
      - install-requirements:
          python: 3.6-stretch
          all: true
          test: true
      - install

      - run:
          name: run black
          command: |
            . venv/bin/activate
            PYFILES=$(circleci tests glob "homeassistant_cli/**/*.py" | circleci tests split)
            black ${PYFILES}
          no_output_timeout: 15m

  pre-test:
    parameters:
      python:
        type: string
    executor:
      name: python
      tag: << parameters.python >>

    steps:
      - checkout
      - docker-prereqs
      - install-requirements:
          python: << parameters.python >>
          test: true

  test:
    parameters:
      python:
        type: string
    executor:
      name: python
      tag: << parameters.python >>
    parallelism: 2

    steps:
      - checkout
      - docker-prereqs
      - install-requirements:
          python: << parameters.python >>
          test: true
      - install

      - run:
          name: run tests with code coverage
          command: |
            . venv/bin/activate
            CC_SWITCH="--cov --cov-report="
            TESTFILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            pytest --timeout=9 --durations=10 --junitxml=test-reports/homeassistant_cli/results.xml -qq -o junit_family=xunit2 -o junit_suite_name=homeassistant-cli -o console_output_style=count -p no:sugar $CC_SWITCH -- ${TESTFILES}
            script/check_dirty
            codecov

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: htmlcov
          destination: cov-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    executor:
      name: python
      tag: 3.6-stretch
    steps:
      - checkout
      - docker-prereqs
      - install-requirements:
          python: 3.6-stretch
          test: true
      - install

      - run:
          name: verify release okey
          command: |
            script/check_release
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            ## echo -e "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
      - run:
          name: do release
          command: |
            . venv/bin/activate
            script/release

workflows:
  version: 2
  build:
    jobs:
      - static-check
      - pre-install-all-requirements:
          requires:
            - static-check
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - black:
          requires:
            - pre-install-all-requirements
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - pre-test:
          name: pre-test 3.6
          requires:
            - static-check
          python: 3.6-stretch
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - pre-test:
          name: pre-test 3.7
          requires:
            - static-check
          python: 3.7-stretch
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - test:
          name: test 3.6
          requires:
            - pre-test 3.6
          python: 3.6-stretch
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - test:
          name: test 3.7
          requires:
            - pre-test 3.7
          python: 3.7-stretch
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/

      # CircleCI does not allow failure yet
      # - test:
      #     name: test 3.8
      #     python: 3.8-rc-stretch
      - deploy:
          requires:
            - test 3.6
            - black
            - test 3.7
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - dev
                - master
